/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.ImageIcon;

/**
 * Esta clase permite pintar la ventana Acerca de, con sus respectivos componentes
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class AcercaDe extends javax.swing.JFrame {

    public AcercaDe() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/about-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelCreado = new javax.swing.JLabel();
        labelMasInfo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 355));
        setPreferredSize(new java.awt.Dimension(400, 355));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Fundacion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 130, 130);

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTitulo.setText("SISTEMA DE GESTIÓN ASDESILLA");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(80, 10, 230, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("yeisson.ochoa72@gmail.com");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 250, 200, 14);

        labelCreado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCreado.setText("Creado el 16 de Septiembre 2014");
        getContentPane().add(labelCreado);
        labelCreado.setBounds(170, 70, 200, 15);

        labelMasInfo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelMasInfo.setText("Para mayor información:");
        getContentPane().add(labelMasInfo);
        labelMasInfo.setBounds(170, 100, 140, 14);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Yeisson Alexander Ochoa Villa");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 230, 180, 14);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Daniela Estrada Monsalve");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 130, 150, 14);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("danielaestradam2013@gmail.com");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 150, 200, 14);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Cristian Hoyos Jaramillo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 180, 140, 14);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("cristianhoyos66@gmail.com");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 200, 200, 14);

        labelVersion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelVersion.setText("Versión: 4");
        getContentPane().add(labelVersion);
        labelVersion.setBounds(170, 50, 70, 15);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Accept-icon.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 290, 110, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCreado;
    private javax.swing.JLabel labelMasInfo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersion;
    // End of variables declaration//GEN-END:variables
}
