/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;
import AccesoDatos.OpCaballos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase permite pintar la ventana Caballos, con sus respectivos componentes, para el manejo de la información equina
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class Caballos extends javax.swing.JFrame {

    public Caballos() {
        initComponents();
        if (InicioSesion.r.equals("2")) {
            btnCrear.setEnabled(false);
        }
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/horse-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNreg = new javax.swing.JLabel();
        txtNreg = new java.awt.TextField();
        labelPruebaAIE = new javax.swing.JLabel();
        jcAnem = new javax.swing.JComboBox();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new java.awt.TextField();
        labelNomDuenio = new javax.swing.JLabel();
        txtApellido2Duenio = new java.awt.TextField();
        labelEdad = new javax.swing.JLabel();
        txtEdad = new java.awt.TextField();
        labelCriadero = new javax.swing.JLabel();
        txtCria = new java.awt.TextField();
        labelInfoProp = new javax.swing.JLabel();
        labelObligatorios = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        labelAp1Duenio = new javax.swing.JLabel();
        labelAp2Duenio = new javax.swing.JLabel();
        txtNombreDuenio = new java.awt.TextField();
        txtApellido1Duenio = new java.awt.TextField();
        labelInfoEquino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Caballos");
        setMinimumSize(new java.awt.Dimension(930, 550));
        getContentPane().setLayout(null);

        labelNreg.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNreg.setText("*Número de registro:");
        getContentPane().add(labelNreg);
        labelNreg.setBounds(30, 110, 140, 15);

        txtNreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNregKeyTyped(evt);
            }
        });
        getContentPane().add(txtNreg);
        txtNreg.setBounds(230, 110, 200, 19);

        labelPruebaAIE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPruebaAIE.setText("*Prueba AIE:");
        getContentPane().add(labelPruebaAIE);
        labelPruebaAIE.setBounds(30, 190, 90, 15);

        jcAnem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Sí", "No" }));
        getContentPane().add(jcAnem);
        jcAnem.setBounds(230, 190, 130, 27);

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombre.setText("*Nombre del equino:");
        getContentPane().add(labelNombre);
        labelNombre.setBounds(520, 110, 121, 15);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(690, 110, 200, 19);

        labelNomDuenio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNomDuenio.setText("*Nombre:");
        labelNomDuenio.setToolTipText("");
        getContentPane().add(labelNomDuenio);
        labelNomDuenio.setBounds(30, 300, 60, 15);

        txtApellido2Duenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido2DuenioKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido2Duenio);
        txtApellido2Duenio.setBounds(230, 340, 200, 19);

        labelEdad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelEdad.setText("*Edad:");
        getContentPane().add(labelEdad);
        labelEdad.setBounds(520, 150, 60, 15);

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(690, 150, 100, 19);

        labelCriadero.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCriadero.setText("*Criadero:");
        getContentPane().add(labelCriadero);
        labelCriadero.setBounds(30, 150, 80, 15);
        getContentPane().add(txtCria);
        txtCria.setBounds(230, 150, 200, 19);

        labelInfoProp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelInfoProp.setText("INFORMACIÓN DEL PROPIETARIO");
        getContentPane().add(labelInfoProp);
        labelInfoProp.setBounds(370, 260, 190, 15);

        labelObligatorios.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelObligatorios.setText("Los campos con * son obligatorios");
        getContentPane().add(labelObligatorios);
        labelObligatorios.setBounds(360, 70, 242, 15);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(760, 440, 110, 34);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-clear-icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(620, 440, 110, 34);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disable-icon.png"))); // NOI18N
        btnEliminar.setText("Deshabilitar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(450, 440, 140, 34);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(310, 440, 100, 34);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(160, 440, 120, 36);

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(30, 440, 100, 34);

        labelAp1Duenio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelAp1Duenio.setText("*Primer Apellido:");
        getContentPane().add(labelAp1Duenio);
        labelAp1Duenio.setBounds(520, 300, 100, 15);

        labelAp2Duenio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelAp2Duenio.setText("Segundo Apellido:");
        getContentPane().add(labelAp2Duenio);
        labelAp2Duenio.setBounds(30, 340, 120, 15);

        txtNombreDuenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDuenioKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreDuenio);
        txtNombreDuenio.setBounds(230, 300, 200, 19);

        txtApellido1Duenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1DuenioKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido1Duenio);
        txtApellido1Duenio.setBounds(690, 300, 200, 19);

        labelInfoEquino.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelInfoEquino.setText("INFORMACIÓN DEL EQUINO");
        getContentPane().add(labelInfoEquino);
        labelInfoEquino.setBounds(380, 30, 180, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Cierra la interfaz y permite regresar al menú principal.
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Menu().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Limpia todos los campos del formulario, asignandoles el valor por defecto
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNreg.setEnabled(true);
        txtNreg.setText("");
        txtNombre.setEnabled(true);
        txtNombre.setText("");
        txtNombreDuenio.setEnabled(true);
        txtNombreDuenio.setText("");
        txtApellido1Duenio.setEnabled(true);
        txtApellido1Duenio.setText("");
        txtApellido2Duenio.setEnabled(true);
        txtApellido2Duenio.setText("");
        txtEdad.setEnabled(true);
        txtEdad.setText("");
        txtCria.setEnabled(true);
        txtCria.setText("");
        jcAnem.setEnabled(true);
        jcAnem.setSelectedIndex(0);
        if (InicioSesion.r.equals("2")) {
            btnCrear.setEnabled(false);
        }else{
            btnCrear.setEnabled(true);
        }
        btnEliminar.setEnabled(false);
        btnEliminar.setText("Deshabilitar");
        btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        btnModificar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed
    /**
     * Llama al método cambiarEstado.
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        cambiarEstado();
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Llama a la interfaz para la visualización de los registros
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        new CaballosRegistros().setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed
    /**
     * Llama al método modificar.
     * @param evt 
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed
    /**
     * Llama al método guardar.
     * @param evt 
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        guardar();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtNregKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNregKeyTyped
      try {
            int num = Integer.parseInt("" + evt.getKeyChar());

        } catch (Exception ev) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNregKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
      try {
            int num = Integer.parseInt("" + evt.getKeyChar());
            evt.consume();
        } catch (Exception ev) {
           
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellido2DuenioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2DuenioKeyTyped
         try {
            int num = Integer.parseInt("" + evt.getKeyChar());
            evt.consume();
        } catch (Exception ev) {
           
        }
    }//GEN-LAST:event_txtApellido2DuenioKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        try {
            int num = Integer.parseInt("" + evt.getKeyChar());
           
        } catch (Exception ev) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreDuenioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDuenioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDuenioKeyTyped

    private void txtApellido1DuenioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1DuenioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1DuenioKeyTyped
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caballos().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public static javax.swing.JButton btnCrear;
    public static javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    public static javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JComboBox jcAnem;
    private javax.swing.JLabel labelAp1Duenio;
    private javax.swing.JLabel labelAp2Duenio;
    private javax.swing.JLabel labelCriadero;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelInfoEquino;
    private javax.swing.JLabel labelInfoProp;
    private javax.swing.JLabel labelNomDuenio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNreg;
    private javax.swing.JLabel labelObligatorios;
    private javax.swing.JLabel labelPruebaAIE;
    public static java.awt.TextField txtApellido1Duenio;
    public static java.awt.TextField txtApellido2Duenio;
    public static java.awt.TextField txtCria;
    public static java.awt.TextField txtEdad;
    public static java.awt.TextField txtNombre;
    public static java.awt.TextField txtNombreDuenio;
    public static java.awt.TextField txtNreg;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que permite guardar la información de un caballo en la base de datos
     * de acuerdo a los datos ingresados
     */
    public void guardar(){
        String Nrege, Nombre, NombreDuenio, Apellido1Duenio, Apellido2Duenio, Edad, Cria, Anem;
        
        Nrege = txtNreg.getText();
        Nombre = txtNombre.getText();
        NombreDuenio = txtNombreDuenio.getText();
        Apellido1Duenio = txtApellido1Duenio.getText();
        Apellido2Duenio = txtApellido2Duenio.getText();
        Edad = txtEdad.getText();
        Cria = txtCria.getText();
        Anem = jcAnem.getSelectedItem().toString();

        if((Nrege == null || Nrege.trim().isEmpty()) || (Nombre == null || Nombre.trim().isEmpty()) || (NombreDuenio == null || NombreDuenio.trim().isEmpty()) || (Apellido1Duenio == null || Apellido1Duenio.trim().isEmpty()) || (Edad == null || Edad.trim().isEmpty()) || (Cria == null || Cria.trim().isEmpty()) || (Anem.equals("Seleccione"))){
            JOptionPane.showMessageDialog(null, "Se deben diligenciar todos los campos obligatorios", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else if(Integer.parseInt(Edad)> 30){
            Edad = null;
            JOptionPane.showMessageDialog(null, "La edad máxima permitida para el campo edad es 30 años", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            int a = OpCaballos.guardar(Nrege, Nombre, NombreDuenio, Apellido1Duenio, Apellido2Duenio, Edad, Cria, Anem);
            if (a == 0) {
               txtNreg.enable();
                txtNreg.setText("");
                txtNombre.setText("");
                txtNombreDuenio.setText("");
                txtApellido1Duenio.setText("");
                txtApellido2Duenio.setText("");
                txtEdad.setText("");
                txtCria.setText("");
                jcAnem.setSelectedIndex(0); 
            }
        }
    }
    
    /**
    * Método que permite cambiar el estado de un registro de caballo existente
    */
    public void cambiarEstado(){
        if(txtNreg.getText() == null || txtNreg.getText().trim().isEmpty()){
            txtNreg.setText(null);
            JOptionPane.showMessageDialog(null, "Debe diligenciar el campo número de registro del equino a cambiar el estado", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }

        if(!txtNreg.getText().trim().isEmpty()){
            JOptionPane x = new JOptionPane();
            if(x.showConfirmDialog(null,"Está seguro que desea cambiar el estado de este registro?")==0){
                OpCaballos.cambiarEstado(txtNreg.getText());
                txtNreg.setEnabled(true);
                txtNreg.setText("");
                txtNombre.setEnabled(true);
                txtNombre.setText("");
                txtNombreDuenio.setEnabled(true);
                txtNombreDuenio.setText("");
                txtApellido1Duenio.setEnabled(true);
                txtApellido1Duenio.setText("");
                txtApellido2Duenio.setEnabled(true);
                txtApellido2Duenio.setText("");
                txtEdad.setEnabled(true);
                txtEdad.setText("");
                txtCria.setEnabled(true);
                txtCria.setText("");
                jcAnem.setEnabled(true);
                jcAnem.setSelectedIndex(0);
                btnCrear.setEnabled(true);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
            }
        }
    }  

    /**
     * Método que permite actualizar la información de un registro de caballo existente
     * con base en los datos ingresados
     */
    public void modificar(){
        String Nrege, Nombre, NombreDuenio, Apellido1Duenio, Apellido2Duenio, Edad, Cria, Anem;

        Nrege = txtNreg.getText();
        Nombre = txtNombre.getText();
        NombreDuenio = txtNombreDuenio.getText();
        Apellido1Duenio = txtApellido1Duenio.getText();
        Apellido2Duenio = txtApellido2Duenio.getText();
        Edad = txtEdad.getText();
        Cria = txtCria.getText();
        Anem = jcAnem.getSelectedItem().toString();

        if((Nrege == null || Nrege.trim().isEmpty()) || (Nombre == null || Nombre.trim().isEmpty()) || (NombreDuenio == null || NombreDuenio.trim().isEmpty()) || (Apellido1Duenio == null || Apellido1Duenio.trim().isEmpty()) || (Edad == null || Edad.trim().isEmpty()) || (Cria == null || Cria.trim().isEmpty()) || (Anem.equals("Seleccione"))){
            JOptionPane.showMessageDialog(null, "Se deben diligenciar todos los campos obligatorios", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else if(Integer.parseInt(Edad)> 30){
            Edad = null;
            JOptionPane.showMessageDialog(null, "La edad máxima permitida para el campo edad es 30 años", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            OpCaballos.modificar(Nrege, Nombre, NombreDuenio, Apellido1Duenio, Apellido2Duenio, Edad, Cria, Anem);
            txtNreg.enable();
            txtNreg.setText("");
            txtNombre.setText("");
            txtNombreDuenio.setText("");
            txtApellido1Duenio.setText("");
            txtApellido2Duenio.setText("");
            txtEdad.setText("");
            txtCria.setText("");
            jcAnem.setSelectedIndex(0);
            btnCrear.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnEliminar.setText("Deshabilitar");
            btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        }
    }
}
