/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.OpCaballos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase permite pintar la ventana para la búsqueda de registros de los Caballos
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class CaballosRegistros extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Map<String, String> p;

    public CaballosRegistros() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/horse-icon.png")).getImage());
        
        dtm = (DefaultTableModel) Registros.getModel();
        if(dtm.getRowCount()!=0){
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i-=1;
            }
        }
        try{
            ArrayList <Object[]> l = OpCaballos.obtenerRegistros();
            for (int i = 0; i < l.size(); i++) {
                dtm.addRow(l.get(i));
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Registros = new javax.swing.JTable();
        jcCaballo = new javax.swing.JComboBox();
        labelNregEquino = new javax.swing.JLabel();
        btnBusqueda = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtDocCab = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(828, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de registro", "Nombre", "Edad", "Criadero", "Prueba AIE", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(Registros);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 800, 280);

        jcCaballo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(jcCaballo);
        jcCaballo.setBounds(540, 100, 140, 27);

        labelNregEquino.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNregEquino.setText("Número de registro del equino:");
        getContentPane().add(labelNregEquino);
        labelNregEquino.setBounds(90, 100, 170, 15);

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBusqueda.setToolTipText("La búsqueda se  puede generar a partir de los primeros números del registro");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusqueda);
        btnBusqueda.setBounds(460, 90, 50, 30);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(30, 170, 125, 34);

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/more-details-icon.png"))); // NOI18N
        btnDetalles.setText("Ver detalles");
        btnDetalles.setEnabled(false);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalles);
        btnDetalles.setBounds(170, 170, 140, 34);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disable-icon.png"))); // NOI18N
        btnEliminar.setText("Deshabilitar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(330, 170, 140, 34);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-clear-icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(500, 170, 137, 34);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(660, 170, 137, 34);
        getContentPane().add(txtDocCab);
        txtDocCab.setBounds(270, 100, 180, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Habilita el botón Ver detalles en caso de que se seleccione algún registro en la tabla.
     * @param evt 
     */
    private void RegistrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosMousePressed
        btnDetalles.setEnabled(true);
        if (InicioSesion.r.equals("2")) {
            btnEliminar.setEnabled(false);
            btnEliminar.setText("Deshabilitar");
            btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        }else{
            String estado = Registros.getValueAt(Registros.getSelectedRow(), 5).toString();
            if (estado.equals("Activo")) {
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
            }else{
                btnEliminar.setText("Habilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/enable-icon.png")));
            }
            btnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_RegistrosMousePressed

    /**
     * Búsqueda de los caballos coincidentes según un carácter ingresado
     * @param evt 
     */
    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        if(txtDocCab.getText() == null || txtDocCab.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar por lo menos un carácter del número de registro del equino", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                jcCaballo.removeAllItems();
                p = OpCaballos.obtenerCaballos(txtDocCab.getText());
                Iterator it = p.keySet().iterator();
                if (p.size()>0) {
                    //JOptionPane.showMessageDialog(null, "Se han encontrado coincidencias");
                }else{
                    //JOptionPane.showMessageDialog(null, "No se han encontrado coincidencias");
                }
                jcCaballo.addItem("Seleccione");
                while(it.hasNext()){
                    jcCaballo.addItem(p.get(it.next()));
                }
                //txtDocCab.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(CaballosRegistros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    /**
     * Llama al método buscar
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Obtiene la información del registro de caballo de acuerdo a los datos de la tabla
     * y los asigna al formulario, además deshabilita el botón Crear
     * y habilita el botón modificar
     * @param evt 
     */
    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
            String identificacion = Registros.getValueAt(Registros.getSelectedRow(), 0).toString();
            String nombre = Registros.getValueAt(Registros.getSelectedRow(), 1).toString();
            String edad = Registros.getValueAt(Registros.getSelectedRow(), 2).toString();
            String criadero = Registros.getValueAt(Registros.getSelectedRow(), 3).toString();
            String anemia = Registros.getValueAt(Registros.getSelectedRow(), 4).toString();
            OpCaballos.buscar(identificacion);
            Caballos.txtNreg.enable(false);
            Caballos.txtNreg.setText(identificacion);
            if (InicioSesion.r.equals("2")) {
                Caballos.txtNombre.setEnabled(false);
                Caballos.txtNombre.setText(nombre);
                Caballos.txtNombreDuenio.setEnabled(false);
                Caballos.txtNombreDuenio.setText(OpCaballos.getNombreDuenio());
                Caballos.txtApellido1Duenio.setEnabled(false);
                Caballos.txtApellido1Duenio.setText(OpCaballos.getApellido1Duenio());
                Caballos.txtApellido2Duenio.setEnabled(false);
                Caballos.txtApellido2Duenio.setText(OpCaballos.getApellido2Duenio());
                Caballos.txtEdad.setEnabled(false);
                Caballos.txtEdad.setText(edad);
                Caballos.txtCria.setEnabled(false);
                Caballos.txtCria.setText(criadero);
                Caballos.jcAnem.setEnabled(false);
                Caballos.jcAnem.setSelectedItem(anemia);
                Caballos.btnModificar.setEnabled(false);
                Caballos.btnEliminar.setEnabled(false);
                Caballos.btnEliminar.setText("Deshabilitar");
                Caballos.btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
            }else{
                if (OpCaballos.getEstado().equals("Activo")) {
                    Caballos.txtNombre.setEnabled(true);
                    Caballos.txtNombre.setText(nombre);
                    Caballos.txtNombreDuenio.setEnabled(true);
                    Caballos.txtNombreDuenio.setText(OpCaballos.getNombreDuenio());
                    Caballos.txtApellido1Duenio.setEnabled(true);
                    Caballos.txtApellido1Duenio.setText(OpCaballos.getApellido1Duenio());
                    Caballos.txtApellido2Duenio.setEnabled(true);
                    Caballos.txtApellido2Duenio.setText(OpCaballos.getApellido2Duenio());
                    Caballos.txtEdad.setEnabled(true);
                    Caballos.txtEdad.setText(edad);
                    Caballos.txtCria.setEnabled(true);
                    Caballos.txtCria.setText(criadero);
                    Caballos.jcAnem.setEnabled(true);
                    Caballos.jcAnem.setSelectedItem(anemia);
                    Caballos.btnModificar.setEnabled(true);
                    Caballos.btnEliminar.setEnabled(true);
                    Caballos.btnEliminar.setText("Deshabilitar");
                    Caballos.btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
                }else{
                    Caballos.txtNombre.setEnabled(false);
                    Caballos.txtNombre.setText(nombre);
                    Caballos.txtNombreDuenio.setEnabled(false);
                    Caballos.txtNombreDuenio.setText(OpCaballos.getNombreDuenio());
                    Caballos.txtApellido1Duenio.setEnabled(false);
                    Caballos.txtApellido1Duenio.setText(OpCaballos.getApellido1Duenio());
                    Caballos.txtApellido2Duenio.setEnabled(false);
                    Caballos.txtApellido2Duenio.setText(OpCaballos.getApellido2Duenio());
                    Caballos.txtEdad.setEnabled(false);
                    Caballos.txtEdad.setText(edad);
                    Caballos.txtCria.setEnabled(false);
                    Caballos.txtCria.setText(criadero);
                    Caballos.jcAnem.setEnabled(false);
                    Caballos.jcAnem.setSelectedItem(anemia);
                    Caballos.btnModificar.setEnabled(false);
                    Caballos.btnEliminar.setEnabled(true);
                    Caballos.btnEliminar.setText("Habilitar");
                    Caballos.btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/enable-icon.png")));
                }
            }
            OpCaballos.setNreg("");
            OpCaballos.setNombre("");
            OpCaballos.setNombreDuenio("");
            OpCaballos.setApellido1Duenio("");
            OpCaballos.setApellido2Duenio("");
            OpCaballos.setEdad("");
            OpCaballos.setCria("");
            OpCaballos.setPruebaAIE("");
            Caballos.btnCrear.setEnabled(false);
            
            this.setVisible(false);
    }//GEN-LAST:event_btnDetallesActionPerformed

    /**
     * Llama al método cambiar estado
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        cambiarEstado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Limpia todos los campos del formulario, asignandoles el valor por defecto
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        jcCaballo.removeAllItems();
        jcCaballo.addItem("Seleccione");
        txtDocCab.setText("");
        btnDetalles.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        if(dtm.getRowCount()!=0){
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i-=1;
            }
        }
        try{
            ArrayList <Object[]> l = OpCaballos.obtenerRegistros();
            for (int i = 0; i < l.size(); i++) {
                dtm.addRow(l.get(i));
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Regresar al menú principal
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaballosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaballosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaballosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaballosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaballosRegistros().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Registros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcCaballo;
    private javax.swing.JLabel labelNregEquino;
    private java.awt.TextField txtDocCab;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que permite buscar un registro de un caballo de acuerdo a su código
     * y muestra la información obtenida en la tabla de registros.
     */
    public void buscar() {
        String id;
        ArrayList <Object[]> l;
        id = null;
        
        if (!"Seleccione".equals(jcCaballo.getSelectedItem().toString())) {
            for (Map.Entry<String, String> pacientes : p.entrySet()){
                String u = pacientes.getKey();
                if (jcCaballo.getSelectedItem().toString().equals(pacientes.getValue())) {
                    id = u;
                }
            }
        }
        
        if(id == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un caballo a buscar", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            l = OpCaballos.buscarRegistros(id);
            if(l.size()>0){
                btnDetalles.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
                if(dtm.getRowCount()!=0){
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        dtm.removeRow(i);
                        i-=1;
                    }
                }
                try{
                    for (int i = 0; i < l.size(); i++) {
                        dtm.addRow(l.get(i));
                    }
                }catch(Exception e){
                    System.out.println("Error: "+e);
                }
            }
        }
    }
    
    /**
     * Método que permite cambiar el estado de un registro existente
     */
    public void cambiarEstado() {
        String identificacion = Registros.getValueAt(Registros.getSelectedRow(), 0).toString();
        if (identificacion == null || identificacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe diligenciar el campo número de registro del equino a cambiar el estado", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }

        if (!identificacion.trim().isEmpty()) {
            JOptionPane x = new JOptionPane();
            if(x.showConfirmDialog(null,"Está seguro que desea cambiar el estado de este registro?")==0){
                OpCaballos.cambiarEstado(identificacion);
                jcCaballo.removeAllItems();
                jcCaballo.addItem("Seleccione");
                btnDetalles.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
                int k = 0;
                if(dtm.getRowCount()!=0){
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        dtm.removeRow(i);
                        i-=1;
                    }
                }
                try{
                    ArrayList <Object[]> l = OpCaballos.obtenerRegistros();
                    for (int i = 0; i < l.size(); i++) {
                        dtm.addRow(l.get(i));
                    }
                }catch(Exception e){
                    System.out.println("Error: "+e);
                }
            }
        }
    }
}
