/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.OpInicio;
import AccesoDatos.OpUsuarios;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase permite pintar la ventana Inicio de Sesión, con sus respectivos componentes, para el manejo del ingreso a la aplicación
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class InicioSesion extends javax.swing.JFrame {
    public static String r;
    public static String usuario;
    
    public InicioSesion() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/login.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new java.awt.TextField();
        txtContraseña = new javax.swing.JPasswordField();
        labelUsuario = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        labelContrasenna = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inicio de sesión");
        setMinimumSize(new java.awt.Dimension(359, 398));
        setResizable(false);
        getContentPane().setLayout(null);

        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(160, 170, 133, 29);
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(160, 230, 133, 33);

        labelUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelUsuario.setText("Usuario:");
        getContentPane().add(labelUsuario);
        labelUsuario.setBounds(70, 170, 52, 15);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Fundacion.png"))); // NOI18N
        getContentPane().add(labelLogo);
        labelLogo.setBounds(120, 20, 126, 118);

        labelContrasenna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelContrasenna.setText("Contraseña:");
        getContentPane().add(labelContrasenna);
        labelContrasenna.setBounds(70, 240, 77, 15);

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Accept-icon.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(50, 310, 110, 40);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(200, 310, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que permite controlar el ingreso a la aplicación
     * a partir usuario y una contraseña
     * @param evt 
     */
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        usuario = txtUsuario.getText();
        String clave = txtContraseña.getText();
        OpInicio chadinicio = new OpInicio();
        if ((txtUsuario.getText().length() >= 1) && (txtContraseña.getText().length() >= 1)) {
            try {
                clave = OpUsuarios.hashText(clave);
                boolean v = chadinicio.ingresar(usuario, clave);
                if(v == true){
                    boolean e = chadinicio.ValidarUsuarioActivo(usuario);
                    if (e == true) {
                        if (chadinicio.validarCambioClave(usuario)== true) {
                            new CambiarClave().setVisible(true);
                            setVisible(false);
                        }else{
                            r = chadinicio.validarRol(usuario, clave);
                            new Menu().setVisible(true);
                            setVisible(false);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "El usuario ingresado está deshabilitado", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if ((txtUsuario.getText()).length() < 1 || (txtContraseña.getText()).length() < 1) {
                JOptionPane.showMessageDialog(null, "Digite usuario y contraseña", "Gestión Asdesilla", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    /**
     * Permite salir de la aplicación
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JOptionPane x = new JOptionPane();
        if(x.showConfirmDialog(null,"¿Desea salir del sistema?")==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                new InicioSesion().setVisible(true);
            //}
        //});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelContrasenna;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
