/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase permite pintar la ventana Menú, con sus respectivos componentes, 
 * y de acuerdo al rol asignado a dicho usuario
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        
        initComponents();
        if (InicioSesion.r.equals("2")) {
            JMenuUsuarios.setVisible(false);
            JMenuProfesionales.setVisible(false);
        }
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/menu.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        MenuPpal = new javax.swing.JMenuBar();
        JMenuUsuarios = new javax.swing.JMenu();
        JMenuItemUsuarios = new javax.swing.JMenuItem();
        JMenuProfesionales = new javax.swing.JMenu();
        JMenuItemProfesionales = new javax.swing.JMenuItem();
        JMenuCaballos = new javax.swing.JMenu();
        JMenuItemCaballos = new javax.swing.JMenuItem();
        JMenuFamiliares = new javax.swing.JMenu();
        JMenuItemFamiliares = new javax.swing.JMenuItem();
        JMenuPacientes = new javax.swing.JMenu();
        JMenuItemPacientes = new javax.swing.JMenuItem();
        JMenuDiagnostico = new javax.swing.JMenu();
        JMenuItemEvaluacion = new javax.swing.JMenuItem();
        jMenuTerapias = new javax.swing.JMenu();
        JMenuClinicas = new javax.swing.JMenu();
        JMenuItemFisioterapia = new javax.swing.JMenuItem();
        JMenuItemFonoaudiologia = new javax.swing.JMenuItem();
        JMenuItemPsicologia = new javax.swing.JMenuItem();
        JMenuItemTerapiasAlternativas = new javax.swing.JMenuItem();
        JMenuAnexos = new javax.swing.JMenu();
        JMenuItemConsentimientos = new javax.swing.JMenuItem();
        JMenuItemProgrTerapeutica = new javax.swing.JMenuItem();
        JMenuInforme = new javax.swing.JMenu();
        JMenuItemInforme = new javax.swing.JMenuItem();
        JMenuAyuda = new javax.swing.JMenu();
        JMenuDoc = new javax.swing.JMenu();
        JMenuItemManualU = new javax.swing.JMenuItem();
        JMenuItemManualT = new javax.swing.JMenuItem();
        JMenuItemAcercaDe = new javax.swing.JMenuItem();
        JMenuSalir = new javax.swing.JMenu();
        JMenuItemSalir = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("jMenu3");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenuItem6.setText("jMenuItem6");

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú Asdesilla");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu - 2.png"))); // NOI18N

        JMenuUsuarios.setText("Usuarios");

        JMenuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-icon.png"))); // NOI18N
        JMenuItemUsuarios.setText("Usuarios");
        JMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemUsuariosActionPerformed(evt);
            }
        });
        JMenuUsuarios.add(JMenuItemUsuarios);

        MenuPpal.add(JMenuUsuarios);

        JMenuProfesionales.setText("Profesionales");

        JMenuItemProfesionales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemProfesionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professional-icon.png"))); // NOI18N
        JMenuItemProfesionales.setText("Profesionales");
        JMenuItemProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemProfesionalesActionPerformed(evt);
            }
        });
        JMenuProfesionales.add(JMenuItemProfesionales);

        MenuPpal.add(JMenuProfesionales);

        JMenuCaballos.setText("Caballos");

        JMenuItemCaballos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemCaballos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horse-icon.png"))); // NOI18N
        JMenuItemCaballos.setText("Caballos");
        JMenuItemCaballos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCaballosActionPerformed(evt);
            }
        });
        JMenuCaballos.add(JMenuItemCaballos);

        MenuPpal.add(JMenuCaballos);

        JMenuFamiliares.setText("Familiares");

        JMenuItemFamiliares.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemFamiliares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/family-icon.png"))); // NOI18N
        JMenuItemFamiliares.setText("Familiares");
        JMenuItemFamiliares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemFamiliaresActionPerformed(evt);
            }
        });
        JMenuFamiliares.add(JMenuItemFamiliares);

        MenuPpal.add(JMenuFamiliares);

        JMenuPacientes.setText("Pacientes");

        JMenuItemPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Patients-icon.png"))); // NOI18N
        JMenuItemPacientes.setText("Pacientes");
        JMenuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemPacientesActionPerformed(evt);
            }
        });
        JMenuPacientes.add(JMenuItemPacientes);

        MenuPpal.add(JMenuPacientes);

        JMenuDiagnostico.setText("Diagnóstico");

        JMenuItemEvaluacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemEvaluacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/evaluation-icon.png"))); // NOI18N
        JMenuItemEvaluacion.setText("Evaluación");
        JMenuItemEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemEvaluacionActionPerformed(evt);
            }
        });
        JMenuDiagnostico.add(JMenuItemEvaluacion);

        MenuPpal.add(JMenuDiagnostico);

        jMenuTerapias.setText("Terapias");

        JMenuClinicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clinic therapies icon.png"))); // NOI18N
        JMenuClinicas.setText("Clínicas");

        JMenuItemFisioterapia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemFisioterapia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fisioterapia-icon.png"))); // NOI18N
        JMenuItemFisioterapia.setText("Fisioterapia");
        JMenuItemFisioterapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemFisioterapiaActionPerformed(evt);
            }
        });
        JMenuClinicas.add(JMenuItemFisioterapia);

        JMenuItemFonoaudiologia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemFonoaudiologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fonoaudiologia-icon.png"))); // NOI18N
        JMenuItemFonoaudiologia.setText("Fonoaudiología");
        JMenuItemFonoaudiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemFonoaudiologiaActionPerformed(evt);
            }
        });
        JMenuClinicas.add(JMenuItemFonoaudiologia);

        JMenuItemPsicologia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemPsicologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/psicologia-icon.png"))); // NOI18N
        JMenuItemPsicologia.setText("Psicología");
        JMenuItemPsicologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemPsicologiaActionPerformed(evt);
            }
        });
        JMenuClinicas.add(JMenuItemPsicologia);

        jMenuTerapias.add(JMenuClinicas);

        JMenuItemTerapiasAlternativas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemTerapiasAlternativas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alternative therapies icon.png"))); // NOI18N
        JMenuItemTerapiasAlternativas.setText("Alternativas");
        JMenuItemTerapiasAlternativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemTerapiasAlternativasActionPerformed(evt);
            }
        });
        jMenuTerapias.add(JMenuItemTerapiasAlternativas);

        MenuPpal.add(jMenuTerapias);

        JMenuAnexos.setText("Anexos");

        JMenuItemConsentimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        JMenuItemConsentimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agreement-icon.png"))); // NOI18N
        JMenuItemConsentimientos.setText("Consentimientos");
        JMenuItemConsentimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemConsentimientosActionPerformed(evt);
            }
        });
        JMenuAnexos.add(JMenuItemConsentimientos);

        JMenuItemProgrTerapeutica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemProgrTerapeutica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/therapeutic programming icon.png"))); // NOI18N
        JMenuItemProgrTerapeutica.setText("Programación Terapéutica");
        JMenuItemProgrTerapeutica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemProgrTerapeuticaActionPerformed(evt);
            }
        });
        JMenuAnexos.add(JMenuItemProgrTerapeutica);

        MenuPpal.add(JMenuAnexos);

        JMenuInforme.setText("Informe");

        JMenuItemInforme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medical-report-icon.png"))); // NOI18N
        JMenuItemInforme.setText("Informe");
        JMenuItemInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemInformeActionPerformed(evt);
            }
        });
        JMenuInforme.add(JMenuItemInforme);

        MenuPpal.add(JMenuInforme);

        JMenuAyuda.setText("Ayuda");

        JMenuDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documentation-icon.png"))); // NOI18N
        JMenuDoc.setText("Documentación");

        JMenuItemManualU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemManualU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-manual-icon.png"))); // NOI18N
        JMenuItemManualU.setText("Manual de Usuario");
        JMenuItemManualU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemManualUActionPerformed(evt);
            }
        });
        JMenuDoc.add(JMenuItemManualU);

        JMenuItemManualT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemManualT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/technical-manual-icon.png"))); // NOI18N
        JMenuItemManualT.setText("Manual Técnico");
        JMenuItemManualT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemManualTActionPerformed(evt);
            }
        });
        JMenuDoc.add(JMenuItemManualT);

        JMenuAyuda.add(JMenuDoc);

        JMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/about-icon.png"))); // NOI18N
        JMenuItemAcercaDe.setText("Acerca de...");
        JMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemAcercaDeActionPerformed(evt);
            }
        });
        JMenuAyuda.add(JMenuItemAcercaDe);

        MenuPpal.add(JMenuAyuda);

        JMenuSalir.setText("Salir");

        JMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        JMenuItemSalir.setText("Salir");
        JMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSalirActionPerformed(evt);
            }
        });
        JMenuSalir.add(JMenuItemSalir);

        MenuPpal.add(JMenuSalir);

        setJMenuBar(MenuPpal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permite llamar a la interfaz Pacientes.
     * @param evt 
     */
    private void JMenuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemPacientesActionPerformed
        new Pacientes().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemPacientesActionPerformed

    /**
     * Permite llamar a la interfaz Familiares.
     * @param evt 
     */
    private void JMenuItemFamiliaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemFamiliaresActionPerformed
        new Familiares().setVisible(true);
        this.hide();           
    }//GEN-LAST:event_JMenuItemFamiliaresActionPerformed

    /**
     * Permite llamar a la interfaz Profesionales.
     * @param evt 
     */
    private void JMenuItemProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemProfesionalesActionPerformed
        new Profesionales().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemProfesionalesActionPerformed

    /**
     * Permite cerrar la sesión y regresar al inicio de sesión.
     * @param evt 
     */
    private void JMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSalirActionPerformed
        JOptionPane x = new JOptionPane();
        if(x.showConfirmDialog(null,"¿Desea cerrar sesión?")==0){
            new InicioSesion().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_JMenuItemSalirActionPerformed

    /**
     * Permite llamar a la interfaz Usuarios.
     * @param evt 
     */
    private void JMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemUsuariosActionPerformed
        new Usuarios().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemUsuariosActionPerformed
    /**
     * Permite llamar a la interfaz Caballos.
     * @param evt 
     */
    private void JMenuItemCaballosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCaballosActionPerformed
        new Caballos().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemCaballosActionPerformed
    /**
     * Permite llamar a la interfaz Evaluación.
     * @param evt 
     */
    private void JMenuItemEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemEvaluacionActionPerformed
        new Evaluaciones().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemEvaluacionActionPerformed
    /**
     * Permite llamar a la interfaz Fisioterapia.
     * @param evt 
     */
    private void JMenuItemFisioterapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemFisioterapiaActionPerformed
        new Fisioterapia().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemFisioterapiaActionPerformed
    /**
     * Permite llamar a la interfaz Fonoaudiología.
     * @param evt 
     */
    private void JMenuItemFonoaudiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemFonoaudiologiaActionPerformed
        new Fonoaudiologia().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemFonoaudiologiaActionPerformed
    /**
     * Permite llamar a la interfaz Área Psicosocial.
     * @param evt 
     */
    private void JMenuItemPsicologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemPsicologiaActionPerformed
        new AreaPsicosocial().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemPsicologiaActionPerformed
    /**
     * Permite llamar a la interfaz Terapias alternativas.
     * @param evt 
     */
    private void JMenuItemTerapiasAlternativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemTerapiasAlternativasActionPerformed
        new TerapiasAlternativas().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemTerapiasAlternativasActionPerformed
    /**
     * Permite visualizar el manual de usuario
     * @param evt 
     */
    private void JMenuItemManualUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemManualUActionPerformed
        try {
            File directorio = new File("temp");
            directorio.mkdirs();
            directorio.setWritable(true);
            String archivo = directorio.getCanonicalPath() + File.pathSeparator + "MANUAL DE USUARIO SISTEMA DE GESTION ASDESILLA.pdf";
            File temp = new File(archivo);
            InputStream is = getClass().getResourceAsStream("/Documentacion/MANUAL DE USUARIO SISTEMA DE GESTION ASDESILLA.pdf");
            FileOutputStream archivoDestino = new FileOutputStream(temp);
            FileWriter fw = new FileWriter(temp);
            byte[] buffer = new byte[512*1024];
            int nbLectura;
            while((nbLectura = is.read(buffer)) != -1)
                archivoDestino.write(buffer, 0, nbLectura);
            fw.close();
            archivoDestino.close();
            is.close();
            Desktop.getDesktop().open(temp);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JMenuItemManualUActionPerformed
    /**
     * Permite visualizar el manual técnico
     * @param evt 
     */
    private void JMenuItemManualTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemManualTActionPerformed
        try {
            File directorio = new File("temp");
            directorio.mkdirs();
            directorio.setWritable(true);
            String archivo = directorio.getCanonicalPath() + File.pathSeparator + "MANUAL TECNICO SISTEMA DE GESTION ASDESILLA.pdf";
            File temp = new File(archivo);
            InputStream is = getClass().getResourceAsStream("/Documentacion/MANUAL TECNICO SISTEMA DE GESTION ASDESILLA.pdf");
            FileOutputStream archivoDestino = new FileOutputStream(temp);
            FileWriter fw = new FileWriter(temp);
            byte[] buffer = new byte[512*1024];
            int nbLectura;
            while((nbLectura = is.read(buffer)) != -1)
                archivoDestino.write(buffer, 0, nbLectura);
            fw.close();
            archivoDestino.close();
            is.close();
            Desktop.getDesktop().open(temp);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JMenuItemManualTActionPerformed

   /**
     * Permite visualizar la ventana Acerca de
     * @param evt 
     */
    private void JMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemAcercaDeActionPerformed
        new AcercaDe().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemAcercaDeActionPerformed
    /**
     * Permite llamar a la interfaz Programación Terapéutica.
     * @param evt 
     */
    private void JMenuItemProgrTerapeuticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemProgrTerapeuticaActionPerformed
        new ProgramacionTerapeutica().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemProgrTerapeuticaActionPerformed
    /**
     * Permite llamar a la interfaz Consentimientos.
     * @param evt 
     */
    private void JMenuItemConsentimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemConsentimientosActionPerformed
        new Consentimientos().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemConsentimientosActionPerformed
    /**
     * Permite llamar a la interfaz Informe.
     * @param evt 
     */
    private void JMenuItemInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemInformeActionPerformed
        new Informe().setVisible(true);
        this.hide();
    }//GEN-LAST:event_JMenuItemInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAnexos;
    private javax.swing.JMenu JMenuAyuda;
    public static javax.swing.JMenu JMenuCaballos;
    private javax.swing.JMenu JMenuClinicas;
    private javax.swing.JMenu JMenuDiagnostico;
    private javax.swing.JMenu JMenuDoc;
    public static javax.swing.JMenu JMenuFamiliares;
    private javax.swing.JMenu JMenuInforme;
    private javax.swing.JMenuItem JMenuItemAcercaDe;
    private javax.swing.JMenuItem JMenuItemCaballos;
    private javax.swing.JMenuItem JMenuItemConsentimientos;
    private javax.swing.JMenuItem JMenuItemEvaluacion;
    private javax.swing.JMenuItem JMenuItemFamiliares;
    public static javax.swing.JMenuItem JMenuItemFisioterapia;
    public static javax.swing.JMenuItem JMenuItemFonoaudiologia;
    private javax.swing.JMenuItem JMenuItemInforme;
    private javax.swing.JMenuItem JMenuItemManualT;
    private javax.swing.JMenuItem JMenuItemManualU;
    private javax.swing.JMenuItem JMenuItemPacientes;
    private javax.swing.JMenuItem JMenuItemProfesionales;
    private javax.swing.JMenuItem JMenuItemProgrTerapeutica;
    public static javax.swing.JMenuItem JMenuItemPsicologia;
    private javax.swing.JMenuItem JMenuItemSalir;
    private javax.swing.JMenuItem JMenuItemTerapiasAlternativas;
    private javax.swing.JMenuItem JMenuItemUsuarios;
    public static javax.swing.JMenu JMenuPacientes;
    public static javax.swing.JMenu JMenuProfesionales;
    private javax.swing.JMenu JMenuSalir;
    public static javax.swing.JMenu JMenuUsuarios;
    private javax.swing.JMenuBar MenuPpal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuTerapias;
    // End of variables declaration//GEN-END:variables
}
