/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.OpTerapiasAlternativas;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase permite pintar la ventana para la búsqueda de los registros de Terapias Alternativas
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class TerapiasAlternativasRegistros extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Map<String, String> p;
    Map<Integer, String> td;

    public TerapiasAlternativasRegistros() {
        try{
            initComponents();
            setIconImage (new ImageIcon(getClass().getResource("/Imagenes/alternative therapies icon.png")).getImage());

            td = OpTerapiasAlternativas.obtenerTerapias();
            Iterator t = td.keySet().iterator();
            while(t.hasNext()){
                jcTerapia.addItem(td.get(t.next()));
            }
            dtm = (DefaultTableModel) Registros.getModel();
            if(dtm.getRowCount()!=0){
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    dtm.removeRow(i);
                    i-=1;
                }
            }
            try{
                ArrayList <Object[]> l = OpTerapiasAlternativas.obtenerRegistros();
                for (int i = 0; i < l.size(); i++) {
                    dtm.addRow(l.get(i));
                }
            }catch(Exception e){
                System.out.println("Error: "+e);
            }

        }catch(SQLException ex){
            Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Registros = new javax.swing.JTable();
        labelFecha = new javax.swing.JLabel();
        FechaN = new com.toedter.calendar.JDateChooser();
        btnDetalles = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        labelDoc = new javax.swing.JLabel();
        txtDocPac = new java.awt.TextField();
        btnBusqueda = new javax.swing.JButton();
        jcPaciente = new javax.swing.JComboBox();
        jcTerapia = new javax.swing.JComboBox();
        labelTerapiaAlt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Historia Clínica", "Paciente", "Profesional", "Terapia Alternativa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(Registros);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 1230, 280);

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("Fecha:");
        getContentPane().add(labelFecha);
        labelFecha.setBounds(20, 100, 40, 15);

        FechaN.setDateFormatString("dd-MM-yyyy");
        FechaN.setName("FechaN"); // NOI18N
        getContentPane().add(FechaN);
        FechaN.setBounds(70, 100, 181, 22);

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/more-details-icon.png"))); // NOI18N
        btnDetalles.setText("Ver detalles");
        btnDetalles.setEnabled(false);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalles);
        btnDetalles.setBounds(390, 170, 140, 34);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-clear-icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(610, 170, 137, 34);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(190, 170, 125, 34);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(840, 170, 137, 34);

        labelDoc.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelDoc.setText("Documento Paciente:");
        getContentPane().add(labelDoc);
        labelDoc.setBounds(330, 100, 135, 15);

        txtDocPac.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDocPac);
        txtDocPac.setBounds(460, 100, 170, 19);

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBusqueda.setToolTipText("La búsqueda se  puede generar a partir de los primeros números del documento");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusqueda);
        btnBusqueda.setBounds(640, 90, 50, 30);

        jcPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(jcPaciente);
        jcPaciente.setBounds(700, 100, 190, 27);

        jcTerapia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(jcTerapia);
        jcTerapia.setBounds(1050, 100, 180, 27);

        labelTerapiaAlt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTerapiaAlt.setText("Terapia Alternativa:");
        getContentPane().add(labelTerapiaAlt);
        labelTerapiaAlt.setBounds(930, 100, 110, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1250, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Obtiene la información de la terapia alternativa de acuerdo a los datos de la tabla
     * y los asigna al formulario, además deshabilita el botón Crear
     * @param evt 
     */
    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = Registros.getValueAt(Registros.getSelectedRow(), 0).toString();
            String hc = Registros.getValueAt(Registros.getSelectedRow(), 1).toString();
            String paciente = Registros.getValueAt(Registros.getSelectedRow(), 2).toString();
            String profesional = Registros.getValueAt(Registros.getSelectedRow(), 3).toString();
            String terapia = Registros.getValueAt(Registros.getSelectedRow(), 4).toString();
            TerapiasAlternativas.txtNHC.setText(hc);
            TerapiasAlternativas.jcPaciente.addItem(paciente);
            TerapiasAlternativas.jcPaciente.setSelectedItem(paciente);
            
            TerapiasAlternativas.jcTerapia.setSelectedItem(terapia);
            
            for (Map.Entry<Integer, String> terapias : td.entrySet()){
                if (terapia.equals(terapias.getValue())) {
                    terapia = String.valueOf(terapias.getKey());
                }
            }
            OpTerapiasAlternativas.buscar(fecha, hc, terapia);
            TerapiasAlternativas.FechaEquinoterapia.setEnabled(false);
            TerapiasAlternativas.FechaEquinoterapia.setDate(formatoFecha.parse(fecha));
            TerapiasAlternativas.txtNHC.setEnabled(false);
            TerapiasAlternativas.jcPaciente.setEnabled(false);
            TerapiasAlternativas.jcTerapia.setEnabled(false);
            TerapiasAlternativas.jcCaballo.setEnabled(false);
            
            Map<String, String> c = OpTerapiasAlternativas.obtenerCaballos();
            for (Map.Entry<String, String> caballos : c.entrySet()){
                if (OpTerapiasAlternativas.getCaballo().equals(caballos.getKey())) {
                    TerapiasAlternativas.jcCaballo.addItem(caballos.getValue());
                    TerapiasAlternativas.jcCaballo.setSelectedItem(caballos.getValue());
                }
            }
            TerapiasAlternativas.jcPostPaso.setEnabled(false);
            TerapiasAlternativas.jcPostPaso.setSelectedItem(OpTerapiasAlternativas.getPostPaso());
            TerapiasAlternativas.jcPostTrote.setEnabled(false);
            TerapiasAlternativas.jcPostTrote.setSelectedItem(OpTerapiasAlternativas.getPostTrote());
            TerapiasAlternativas.jcPostGalope.setEnabled(false);
            TerapiasAlternativas.jcPostGalope.setSelectedItem(OpTerapiasAlternativas.getPostGalope());
            TerapiasAlternativas.jcAsientoProf.setEnabled(false);
            TerapiasAlternativas.jcAsientoProf.setSelectedItem(OpTerapiasAlternativas.getAsientoProf());
            TerapiasAlternativas.jcAsientoLig.setEnabled(false);
            TerapiasAlternativas.jcAsientoLig.setSelectedItem(OpTerapiasAlternativas.getAsientoLig());
            TerapiasAlternativas.jcTronco.setEnabled(false);
            TerapiasAlternativas.jcTronco.setSelectedItem(OpTerapiasAlternativas.getTronco());
            TerapiasAlternativas.jcCabeza.setEnabled(false);
            TerapiasAlternativas.jcCabeza.setSelectedItem(OpTerapiasAlternativas.getCabeza());
            TerapiasAlternativas.jcBrazos.setEnabled(false);
            TerapiasAlternativas.jcBrazos.setSelectedItem(OpTerapiasAlternativas.getBrazos());
            TerapiasAlternativas.jcCodos.setEnabled(false);
            TerapiasAlternativas.jcCodos.setSelectedItem(OpTerapiasAlternativas.getCodos());
            TerapiasAlternativas.jcManos.setEnabled(false);
            TerapiasAlternativas.jcManos.setSelectedItem(OpTerapiasAlternativas.getManos());
            TerapiasAlternativas.jcPelvis.setEnabled(false);
            TerapiasAlternativas.jcPelvis.setSelectedItem(OpTerapiasAlternativas.getPelvis());
            TerapiasAlternativas.jcPiernas.setEnabled(false);
            TerapiasAlternativas.jcPiernas.setSelectedItem(OpTerapiasAlternativas.getPiernas());
            TerapiasAlternativas.jcPies.setEnabled(false);
            TerapiasAlternativas.jcPies.setSelectedItem(OpTerapiasAlternativas.getPies());
            TerapiasAlternativas.jcMMontPelvis.setEnabled(false);
            TerapiasAlternativas.jcMMontPelvis.setSelectedItem(OpTerapiasAlternativas.getAyudMontPelvis());
            TerapiasAlternativas.jcMMontPiernas.setEnabled(false);
            TerapiasAlternativas.jcMMontPiernas.setSelectedItem(OpTerapiasAlternativas.getAyudMontPiernas());
            TerapiasAlternativas.jcMMontManos.setEnabled(false);
            TerapiasAlternativas.jcMMontManos.setSelectedItem(OpTerapiasAlternativas.getAyudMontManos());
            TerapiasAlternativas.jcAsientFlexion.setEnabled(false);
            TerapiasAlternativas.jcAsientFlexion.setSelectedItem(OpTerapiasAlternativas.getAyudMontAsientoProf());
            TerapiasAlternativas.jcSalidTrote.setEnabled(false);
            TerapiasAlternativas.jcSalidTrote.setSelectedItem(OpTerapiasAlternativas.getSalidTrote());
            TerapiasAlternativas.jcSalidGalopeTr.setEnabled(false);
            TerapiasAlternativas.jcSalidGalopeTr.setSelectedItem(OpTerapiasAlternativas.getSalidGalopeTr());
            TerapiasAlternativas.jcSalidGalopePaso.setEnabled(false);
            TerapiasAlternativas.jcSalidGalopePaso.setSelectedItem(OpTerapiasAlternativas.getSalidGalopePaso());
            TerapiasAlternativas.jcAltoPaso.setEnabled(false);
            TerapiasAlternativas.jcAltoPaso.setSelectedItem(OpTerapiasAlternativas.getAltoPaso());
            TerapiasAlternativas.jcAltoTrote.setEnabled(false);
            TerapiasAlternativas.jcAltoTrote.setSelectedItem(OpTerapiasAlternativas.getAltoTrote());
            TerapiasAlternativas.jcAltoGalope.setEnabled(false);
            TerapiasAlternativas.jcAltoGalope.setSelectedItem(OpTerapiasAlternativas.getAltoGalope());
            TerapiasAlternativas.jcCirculos.setEnabled(false);
            TerapiasAlternativas.jcCirculos.setSelectedItem(OpTerapiasAlternativas.getCirculos());
            TerapiasAlternativas.jcSerpentinas.setEnabled(false);
            TerapiasAlternativas.jcSerpentinas.setSelectedItem(OpTerapiasAlternativas.getSerpentinas());
            TerapiasAlternativas.jcApoyos.setEnabled(false);
            TerapiasAlternativas.jcApoyos.setSelectedItem(OpTerapiasAlternativas.getApoyos());
            TerapiasAlternativas.jcEquilibrio.setEnabled(false);
            TerapiasAlternativas.jcEquilibrio.setSelectedItem(OpTerapiasAlternativas.getEquilibrio());
            TerapiasAlternativas.jcFlexibilidad.setEnabled(false);
            TerapiasAlternativas.jcFlexibilidad.setSelectedItem(OpTerapiasAlternativas.getFlexibilidad());
            TerapiasAlternativas.jcCoordPsicomotriz.setEnabled(false);
            TerapiasAlternativas.jcCoordPsicomotriz.setSelectedItem(OpTerapiasAlternativas.getCoordPsicomotriz());
            TerapiasAlternativas.jcFuerzaMusc.setEnabled(false);
            TerapiasAlternativas.jcFuerzaMusc.setSelectedItem(OpTerapiasAlternativas.getFuerzaMuscular());
            TerapiasAlternativas.jcManejoEsp.setEnabled(false);
            TerapiasAlternativas.jcManejoEsp.setSelectedItem(OpTerapiasAlternativas.getManejoEsp());
            TerapiasAlternativas.txtObservaciones.setEnabled(false);
            TerapiasAlternativas.txtObservaciones.setText(OpTerapiasAlternativas.getObservaciones());
            TerapiasAlternativas.jcProfesional.setEnabled(false);
            TerapiasAlternativas.jcProfesional.addItem(profesional);
            TerapiasAlternativas.jcProfesional.setSelectedItem(profesional);
            OpTerapiasAlternativas.setFecha("");
            OpTerapiasAlternativas.setIdHistoriaClinica("");
            OpTerapiasAlternativas.setTerapia("");
            OpTerapiasAlternativas.setCaballo("");
            OpTerapiasAlternativas.setPostPaso("");
            OpTerapiasAlternativas.setPostTrote("");
            OpTerapiasAlternativas.setPostGalope("");
            OpTerapiasAlternativas.setAsientoProf("");
            OpTerapiasAlternativas.setAsientoLig("");
            OpTerapiasAlternativas.setTronco("");
            OpTerapiasAlternativas.setCabeza("");
            OpTerapiasAlternativas.setBrazos("");
            OpTerapiasAlternativas.setCodos("");
            OpTerapiasAlternativas.setManos("");
            OpTerapiasAlternativas.setPelvis("");
            OpTerapiasAlternativas.setPiernas("");
            OpTerapiasAlternativas.setPies("");
            OpTerapiasAlternativas.setAyudMontPelvis("");
            OpTerapiasAlternativas.setAyudMontPiernas("");
            OpTerapiasAlternativas.setAyudMontManos("");
            OpTerapiasAlternativas.setAyudMontAsientoProf("");
            OpTerapiasAlternativas.setSalidTrote("");
            OpTerapiasAlternativas.setSalidGalopeTr("");
            OpTerapiasAlternativas.setSalidGalopePaso("");
            OpTerapiasAlternativas.setAltoPaso("");
            OpTerapiasAlternativas.setAltoTrote("");
            OpTerapiasAlternativas.setAltoGalope("");
            OpTerapiasAlternativas.setCirculos("");
            OpTerapiasAlternativas.setSerpentinas("");
            OpTerapiasAlternativas.setApoyos("");
            OpTerapiasAlternativas.setEquilibrio("");
            OpTerapiasAlternativas.setFlexibilidad("");
            OpTerapiasAlternativas.setCoordPsicomotriz("");
            OpTerapiasAlternativas.setFuerzaMuscular("");
            OpTerapiasAlternativas.setManejoEsp("");
            OpTerapiasAlternativas.setObservaciones("");
            OpTerapiasAlternativas.setProfesional("");
            TerapiasAlternativas.txtDocCab.setEnabled(false);
            TerapiasAlternativas.btnBusqueda.setEnabled(false);
            TerapiasAlternativas.txtDocProf.setEnabled(false);
            TerapiasAlternativas.btnBusquedaProf.setEnabled(false);
            TerapiasAlternativas.txtDocPac.setEnabled(false);
            TerapiasAlternativas.btnBusquedaPac.setEnabled(false);
            TerapiasAlternativas.btnCrearTerapiaAlternativa.setEnabled(false);
            this.setVisible(false);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetallesActionPerformed

    /**
     * Limpia todos los campos y restaura los datos de la tabla en caso de haberse hecho una consulta.
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        FechaN.setDate(null);
        jcPaciente.removeAllItems();
        jcPaciente.addItem("Seleccione");
        txtDocPac.setText("");
        jcPaciente.setSelectedIndex(0);
        jcTerapia.setSelectedIndex(0);
        btnDetalles.setEnabled(false);
        if(dtm.getRowCount()!=0){
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i-=1;
            }
        }
        try{
            ArrayList <Object[]> l = OpTerapiasAlternativas.obtenerRegistros();
            for (int i = 0; i < l.size(); i++) {
                dtm.addRow(l.get(i));
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Habilita el botón Ver detalles en caso de que se seleccione algún registro en la tabla.
     * @param evt 
     */
    private void RegistrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosMousePressed
        btnDetalles.setEnabled(true);
    }//GEN-LAST:event_RegistrosMousePressed

    /**
     * Llama al método buscar.
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Cierra la ventana de registros.
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Búsqueda de los pacientes coincidentes según un carácter ingresado
     * @param evt 
     */
    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        if(txtDocPac.getText() == null || txtDocPac.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar por lo menos un carácter del número de identificación del paciente", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                jcPaciente.removeAllItems();
                p = OpTerapiasAlternativas.consultarPacientes(txtDocPac.getText());
                Iterator it = p.keySet().iterator();
                if (p.size()>0) {
                    //JOptionPane.showMessageDialog(null, "Se han encontrado coincidencias");
                }else{
                    //JOptionPane.showMessageDialog(null, "No se han encontrado coincidencias");
                }
                jcPaciente.addItem("Seleccione");
                while(it.hasNext()){
                    jcPaciente.addItem(p.get(it.next()));
                }
                //txtDocPac.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(PacientesRegistros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerapiasAlternativasRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerapiasAlternativasRegistros().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaN;
    private javax.swing.JTable Registros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JComboBox jcPaciente;
    public static javax.swing.JComboBox jcTerapia;
    private javax.swing.JLabel labelDoc;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelTerapiaAlt;
    public static java.awt.TextField txtDocPac;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que permite buscar un registro de una terapia alternativa de acuerdo a la fecha y/o número de identificación digitada
     * y muestra la información obtenida en la tabla de registros.
     */
    public void buscar() {
        String id, diaFecha, mesFecha, annoFecha, fecha, terapia;
        fecha = "";
        id = null;
        terapia = null;
        
        if(FechaN.getDate() != null){
            diaFecha = String.valueOf(FechaN.getCalendar().get(Calendar.DAY_OF_MONTH));
            mesFecha = String.valueOf(FechaN.getCalendar().get(Calendar.MONTH) + 1);
            annoFecha = String.valueOf(FechaN.getCalendar().get(Calendar.YEAR));
            fecha = diaFecha + "/" + mesFecha + "/" + annoFecha;
        }else{
            fecha = null;
        }
        if (!jcPaciente.getSelectedItem().toString().equals("Seleccione")) {
            for (Map.Entry<String, String> pacientes : p.entrySet()){
                String p = pacientes.getKey();
                if (jcPaciente.getSelectedItem().toString().equals(pacientes.getValue())) {
                    id = p;
                }
            }
        }
        
        if (!jcTerapia.getSelectedItem().toString().equals("Seleccione")) {
            for (Map.Entry<Integer, String> terapias : td.entrySet()){
                int td = terapias.getKey();
                if (jcTerapia.getSelectedItem().toString().equals(terapias.getValue())) {
                    terapia = String.valueOf(td);
                }
            }
        }
        
        if(fecha == null && id == null && terapia == null){
            JOptionPane.showMessageDialog(null, "Debe diligenciar una fecha, una terapia o un número de identificación a buscar", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            ArrayList <Object[]> l = OpTerapiasAlternativas.buscarRegistros(fecha, id, terapia);
            if(l.size()>0){
                btnDetalles.setEnabled(false);
                if(dtm.getRowCount()!=0){
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        dtm.removeRow(i);
                        i-=1;
                    }
                }
                try{
                    for (int i = 0; i < l.size(); i++) {
                        dtm.addRow(l.get(i));
                    }
                }catch(Exception e){
                    System.out.println("Error: "+e);
                }
            }
        }
    }
}
