/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.OpUsuarios;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase permite pintar la ventana para la búsqueda de los registros de Usuarios
 * @author Cristian A. Hoyos Jaramillo
 * @author Daniela Estrada Monsalve
 * @author Yeisson A. Ochoa Villa
 */
public class UsuariosRegistros extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Map<String, String> p;

    public UsuariosRegistros() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes/user-icon.png")).getImage());
        dtm = (DefaultTableModel) Registros.getModel();
        if(dtm.getRowCount()!=0){
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i-=1;
            }
        }
        try{
            ArrayList <Object[]> l = OpUsuarios.obtenerRegistros();
            for (int i = 0; i < l.size(); i++) {
                dtm.addRow(l.get(i));
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Registros = new javax.swing.JTable();
        labelDoc = new javax.swing.JLabel();
        jcUsuario = new javax.swing.JComboBox();
        btnDetalles = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtDocUsu = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(822, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre", "Primer Apellido", "Segundo Apellido", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(Registros);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 800, 280);

        labelDoc.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelDoc.setText("Documento Usuario:");
        getContentPane().add(labelDoc);
        labelDoc.setBounds(90, 90, 115, 15);

        jcUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        getContentPane().add(jcUsuario);
        jcUsuario.setBounds(480, 90, 210, 27);

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/more-details-icon.png"))); // NOI18N
        btnDetalles.setText("Ver detalles");
        btnDetalles.setEnabled(false);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalles);
        btnDetalles.setBounds(170, 170, 140, 34);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actions-edit-clear-icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(490, 170, 137, 34);

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBusqueda.setToolTipText("La búsqueda se  puede generar a partir de los primeros números del documento");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusqueda);
        btnBusqueda.setBounds(410, 80, 50, 30);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log-Out-icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(650, 170, 137, 34);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(30, 170, 125, 34);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disable-icon.png"))); // NOI18N
        btnEliminar.setText("Deshabilitar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(330, 170, 140, 34);
        getContentPane().add(txtDocUsu);
        txtDocUsu.setBounds(210, 90, 190, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Obtiene la información de un usuario de acuerdo a los datos de la tabla
     * y los asigna al formulario, además deshabilita el botón Crear
     * y habilita el botón modificar.
     * @param evt 
     */
    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        try {
            String identificacion = Registros.getValueAt(Registros.getSelectedRow(), 0).toString();
            
            OpUsuarios.buscar(identificacion);
            Usuarios.txtNdoc.setEnabled(false);
            Usuarios.txtNdoc.setText(OpUsuarios.getId());
            if (OpUsuarios.getEstado().equals("Activo")) {
                TreeMap<Integer, String> t = OpUsuarios.obtenerTipoDoc();
                for (Map.Entry<Integer, String> tipoDocs : t.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getTipoDocumento()) == tipoDocs.getKey()) {
                        Usuarios.jcTipoDoc.setEnabled(true);
                        Usuarios.jcTipoDoc.setSelectedItem(tipoDocs.getValue());
                    }
                }
                
                Usuarios.txtNombre.setEnabled(true);
                Usuarios.txtNombre.setText(OpUsuarios.getNombre());
                Usuarios.txtApellido1.setEnabled(true);
                Usuarios.txtApellido1.setText(OpUsuarios.getApellido1());
                Usuarios.txtApellido2.setEnabled(true);
                Usuarios.txtApellido2.setText(OpUsuarios.getApellido2());
                
                TreeMap<Integer, String> o = OpUsuarios.obtenerCargos();
                for (Map.Entry<Integer, String> ocupaciones : o.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getOcupacion()) == ocupaciones.getKey()) {
                        Usuarios.jcCargo.setEnabled(true);
                        Usuarios.jcCargo.setSelectedItem(ocupaciones.getValue());
                    }
                }
                Usuarios.txtUsuario.setEnabled(false);
                Usuarios.txtUsuario.setText(OpUsuarios.getUsuario());
                Usuarios.txtClave.setEnabled(false);
                Usuarios.txtValidarClave.setEnabled(false);
                
                TreeMap<Integer, String> l = OpUsuarios.obtenerPerfiles();
                for (Map.Entry<Integer, String> perfiles : l.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getPerfil()) == perfiles.getKey()) {
                        Usuarios.jcPerfil.setEnabled(true);
                        Usuarios.jcPerfil.setSelectedItem(perfiles.getValue());
                    }
                }
                Usuarios.btnGenerarClave.setEnabled(true);
                Usuarios.btnModificar.setEnabled(true);
                Usuarios.btnEliminar.setEnabled(true);
                Usuarios.btnEliminar.setText("Deshabilitar");
                Usuarios.btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
            }else{
                TreeMap<Integer, String> t = OpUsuarios.obtenerTipoDoc();
                for (Map.Entry<Integer, String> tipoDocs : t.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getTipoDocumento()) == tipoDocs.getKey()) {
                        Usuarios.jcTipoDoc.setEnabled(false);
                        Usuarios.jcTipoDoc.setSelectedItem(tipoDocs.getValue());
                    }
                }
                
                Usuarios.txtNombre.setEnabled(false);
                Usuarios.txtNombre.setText(OpUsuarios.getNombre());
                Usuarios.txtApellido1.setEnabled(false);
                Usuarios.txtApellido1.setText(OpUsuarios.getApellido1());
                Usuarios.txtApellido2.setEnabled(false);
                Usuarios.txtApellido2.setText(OpUsuarios.getApellido2());
                
                TreeMap<Integer, String> o = OpUsuarios.obtenerCargos();
                for (Map.Entry<Integer, String> ocupaciones : o.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getOcupacion()) == ocupaciones.getKey()) {
                        Usuarios.jcCargo.setEnabled(false);
                        Usuarios.jcCargo.setSelectedItem(ocupaciones.getValue());
                    }
                }
                Usuarios.txtUsuario.setEnabled(false);
                Usuarios.txtUsuario.setText(OpUsuarios.getUsuario());
                Usuarios.txtClave.setEnabled(false);
                Usuarios.txtValidarClave.setEnabled(false);
                
                TreeMap<Integer, String> l = OpUsuarios.obtenerPerfiles();
                for (Map.Entry<Integer, String> perfiles : l.entrySet()){
                    if (Integer.parseInt(OpUsuarios.getPerfil()) == perfiles.getKey()) {
                        Usuarios.jcPerfil.setEnabled(false);
                        Usuarios.jcPerfil.setSelectedItem(perfiles.getValue());
                    }
                }
                Usuarios.btnGenerarClave.setEnabled(false);
                Usuarios.btnModificar.setEnabled(false);
                Usuarios.btnEliminar.setEnabled(true);
                Usuarios.btnEliminar.setText("Habilitar");
                Usuarios.btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/enable-icon.png")));
            }
            OpUsuarios.setId("");
            OpUsuarios.setTipoDocumento("");
            OpUsuarios.setNombre("");
            OpUsuarios.setApellido1("");
            OpUsuarios.setApellido2("");
            OpUsuarios.setOcupacion("");
            OpUsuarios.setUsuario("");
            OpUsuarios.setClave("");
            OpUsuarios.setPerfil("");
            OpUsuarios.setEstado("");
            this.setVisible(false);
            Usuarios.btnCrear.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(UsuariosRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetallesActionPerformed

    /**
     * Limpia todos los campos y restaura los datos de la tabla en caso de haberse hecho una consulta.
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        jcUsuario.removeAllItems();
        jcUsuario.addItem("Seleccione");
        txtDocUsu.setText("");
        btnDetalles.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setText("Deshabilitar");
        btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        dtm = (DefaultTableModel) Registros.getModel();
        if(dtm.getRowCount()!=0){
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i-=1;
            }
        }
        try{
            ArrayList <Object[]> l = OpUsuarios.obtenerRegistros();
            for (int i = 0; i < l.size(); i++) {
                dtm.addRow(l.get(i));
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Habilita el botón Ver detalles en caso de que se seleccione algún registro en la tabla.
     * @param evt 
     */
    private void RegistrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosMousePressed
        btnDetalles.setEnabled(true);
        btnEliminar.setEnabled(true);
        String estado = Registros.getValueAt(Registros.getSelectedRow(), 4).toString();
        if (estado.equals("Activo")) {
            btnEliminar.setText("Deshabilitar");
            btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
        }else{
            btnEliminar.setText("Habilitar");
            btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/enable-icon.png")));
        }
    }//GEN-LAST:event_RegistrosMousePressed

    /**
     * Búsqueda de los usuarios coincidentes según un carácter ingresado
     * @param evt 
     */
    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        if(txtDocUsu.getText() == null || txtDocUsu.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar por lo menos un carácter del número de identificación del usuario", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                jcUsuario.removeAllItems();
                p = OpUsuarios.obtenerUsuarios(txtDocUsu.getText());
                Iterator it = p.keySet().iterator();
                if (p.size()>0) {
                    //JOptionPane.showMessageDialog(null, "Se han encontrado coincidencias");
                }else{
                    //JOptionPane.showMessageDialog(null, "No se han encontrado coincidencias");
                }
                jcUsuario.addItem("Seleccione");
                while(it.hasNext()){
                    jcUsuario.addItem(p.get(it.next()));
                }
                //txtDocUsu.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(UsuariosRegistros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    /**
     * Cierra la ventana de registros.
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed
    /**
     * Llama al método buscar
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed
    /**
     * Llama al método cambiar estado
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        cambiarEstado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosRegistros().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Registros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcUsuario;
    private javax.swing.JLabel labelDoc;
    private java.awt.TextField txtDocUsu;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que permite buscar un registro de un usuario de acuerdo al número de identificación digitado
     * y muestra la información obtenida en la tabla de registros.
     */
    public void buscar() {
        String id;
        ArrayList <Object[]> l;
        id = null;
        
        /*if(id.equals("Seleccione")){
            id = null;
        }*/
        
        if (!"Seleccione".equals(jcUsuario.getSelectedItem().toString())) {
            for (Map.Entry<String, String> usuarios : p.entrySet()){
                String u = usuarios.getKey();
                if (jcUsuario.getSelectedItem().toString().equals(usuarios.getValue())) {
                    id = u;
                }
            }
        }
        
        if(id == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario a buscar", "Gestión Asdesilla", JOptionPane.ERROR_MESSAGE);
        }else{
            l = OpUsuarios.buscarRegistros(id);
            if(l.size()>0){
                btnDetalles.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
                dtm = (DefaultTableModel) Registros.getModel();
                if(dtm.getRowCount()!=0){
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        dtm.removeRow(i);
                        i-=1;
                    }
                }
                try{
                    for (int i = 0; i < l.size(); i++) {
                        dtm.addRow(l.get(i));
                    }
                }catch(Exception e){
                    System.out.println("Error: "+e);
                }
            }
        }
    }
    
    /**
    * Método que permite cambiar el estado de un usuario registrado 
    * de acuerdo a la identificación digitada.
    */
    public void cambiarEstado(){
        String identificacion = Registros.getValueAt(Registros.getSelectedRow(), 0).toString();
        if(identificacion == null || identificacion.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar el registro a cambiar el estado");
        }

        if(!identificacion.trim().isEmpty()){
            JOptionPane x = new JOptionPane();
            if(x.showConfirmDialog(null,"Está seguro que desea cambiar el estado de este registro?")==0){
                OpUsuarios.cambiarEstado(identificacion);
                jcUsuario.removeAllItems();
                jcUsuario.addItem("Seleccione");
                btnDetalles.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEliminar.setText("Deshabilitar");
                btnEliminar.setIcon(new ImageIcon(getClass().getResource("/Imagenes/disable-icon.png")));
                dtm = (DefaultTableModel) Registros.getModel();
                if(dtm.getRowCount()!=0){
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        dtm.removeRow(i);
                        i-=1;
                    }
                }
                try{
                    ArrayList <Object[]> l = OpUsuarios.obtenerRegistros();
                    for (int i = 0; i < l.size(); i++) {
                        dtm.addRow(l.get(i));
                    }
                }catch(Exception e){
                    System.out.println("Error: "+e);
                }
            }
        }
    }
}
